### PR TITLE
Add signed_url method to AWS::S3::File and tests

### PR DESCRIPTION
**Pull request by leejo**
N.B. this builds upon changes from PR #6 and #8.

This returns the signed URL for public access to a file, the expiry time can be passed into the method or will default to now + 1 hour in the future. Add perldoc and tests for these changes, update MANIFEST.

Although the URL is built on the client side this has been implemented using the same structure as other requests with a GetPreSignedUrl class that uses the AWS::S3:Roles::Request role to get at the _uri attribute. We don't actually go out to AWS for this method, but who knows what the future holds?

### CODE REVIEW

**Comment by jdrago999** [comment]
Looks great - thanks for putting this together.

**Comment by leejo** [comment]
Thanks - i see this still hasn't made it to CPAN? If you need someone to take over maintenance of the module i'm happy to do so.

**Comment by leejo** [comment]
cpan: LEEJO

Thanks!
Lee.
 
LJ
Lee Johnson
http://leejo.github.io/

**Comment by jdrago999** [comment]
Ok you are now co-maintainer.  I have merged changes, bumped version to 0.040 and whatnot.  Please do what you wish.  THANK YOU!

**Comment by leejo** [comment]
Thanks! I've just pushed out 0.050 since there's a file missing from the MANIFEST, however there are some missing permissions that i think you might need to fix:

The following report has been written by the PAUSE namespace indexer.
Please contact modules@perl.org if there are any open questions.

  User: LEEJO (Lee Johnson)
  Distribution file: AWS-S3-0.050.tar.gz
  Number of files: 37
  *.pm files: 25
  README: AWS-S3-0.050/README.markdown
  META-File: AWS-S3-0.050/META.json
  META-Parser: Parse::CPAN::Meta 1.4404
  META-driven index: no
  Timestamp of file: Thu Oct 23 12:52:27 2014 UTC
  Time of this run: Thu Oct 23 12:54:13 2014 UTC

# Status of this distro: Permission missing

The following packages (grouped by status) have been found in the distro:

# Status: Permission missing

    module : AWS::S3::Request::CreateBucket
    version: undef
    in file: AWS-S3-0.050/lib/AWS/S3/Request/CreateBucket.pm
    status : Not indexed because permission missing. Current registered
            primary maintainer is JOHND. Hint: you can always find the
            legitimate maintainer(s) on PAUSE under "View Permissions".

    module : AWS::S3::Request::DeleteBucket
    version: undef
    in file: AWS-S3-0.050/lib/AWS/S3/Request/DeleteBucket.pm
    status : Not indexed because permission missing. Current registered
            primary maintainer is JOHND. Hint: you can always find the
            legitimate maintainer(s) on PAUSE under "View Permissions".

    module : AWS::S3::Request::DeleteFile
    version: undef
    in file: AWS-S3-0.050/lib/AWS/S3/Request/DeleteFile.pm
    status : Not indexed because permission missing. Current registered
            primary maintainer is JOHND. Hint: you can always find the
            legitimate maintainer(s) on PAUSE under "View Permissions".

    module : AWS::S3::Request::DeleteMulti
    version: undef
    in file: AWS-S3-0.050/lib/AWS/S3/Request/DeleteMulti.pm
    status : Not indexed because permission missing. Current registered
            primary maintainer is JOHND. Hint: you can always find the
            legitimate maintainer(s) on PAUSE under "View Permissions".

    module : AWS::S3::Request::GetFileInfo
    version: undef
    in file: AWS-S3-0.050/lib/AWS/S3/Request/GetFileInfo.pm
    status : Not indexed because permission missing. Current registered
            primary maintainer is JOHND. Hint: you can always find the
            legitimate maintainer(s) on PAUSE under "View Permissions".

    module : AWS::S3::Roles::BucketAction
    version: undef
    in file: AWS-S3-0.050/lib/AWS/S3/Roles/BucketAction.pm
    status : Not indexed because permission missing. Current registered
            primary maintainer is JOHND. Hint: you can always find the
            legitimate maintainer(s) on PAUSE under "View Permissions".

    module : AWS::S3::Roles::Request
    version: undef
    in file: AWS-S3-0.050/lib/AWS/S3/Roles/Request.pm
    status : Not indexed because permission missing. Current registered
            primary maintainer is JOHND. Hint: you can always find the
            legitimate maintainer(s) on PAUSE under "View Permissions".

    module : AWS::S3::Signer
    version: undef
    in file: AWS-S3-0.050/lib/AWS/S3/Signer.pm
    status : Not indexed because permission missing. Current registered
            primary maintainer is JOHND. Hint: you can always find the
            legitimate maintainer(s) on PAUSE under "View Permissions".
 
LJ
Lee Johnson
http://leejo.github.io/

**Pull request merged**
