### PR TITLE
Added support for storage class

### PR DESCRIPTION
**Pull request by robin13**
Also normalised formatting with perltidy.  If you don't like the style, perhaps you could modify the .perltidyrc file with your formatting rules?

### CODE REVIEW

**Comment by jdrago999** [comment]
Robin - thank you for your hard work!

**Comment by EvanCarroll** [comment]
Cuddeled elses and elseif..

**Comment by robin13** [comment]
regarding cuddling: have you got a .perltidyrc with your favoured style?  Happy to add a git hook to make it conform, if there is a definition to conform to.

Sorry about mashed contenttype.  Have completed that re-factor and pushed changed version.

**Comment by jdrago999** [comment]
I'm not picky about style - what you are doing is great!

Will apply this pull now.

**Pull request merged**
